version: "3.8"
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=booking
      - DB_USERNAME=postgres
      - DB_PASSWORD=qwerty
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: booking
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "8080:8080"
volumes:
  pgdata:
